apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-manager-database-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.db.size | default "5Gi" }}